; 看不懂的标签请自行查阅说明书
; Ares
[GlobalControls]
AllowParallelAIQueues=false
; 禁用 AI 克隆工厂（2 个建造厂就同时起两座建筑）
AllowBypassBuildLimit=false,false,false
; 禁用 AI 超过 BuildLimit 限制的数量生产，默认禁用，可以自己重新对不同难度进行设定
SuperWeaponSidebarKeysEnabled=true
; 开启快捷键发射超武

[GenericPrerequisites]
POWER=GAPOWR,NAPOWR,YAPOWR
FACTORY=GAWEAP,NAWEAP,YAWEAP
BARRACKS=NAHAND,GAPILE,YABRCK
RADAR=GAAIRC,NARADR,AMRADR,NAPSIS
Tech=GATECH,NATECH,YATECH
PROC=GAREFN,NAREFN,YAREFN

[General]
; Ares
ReturnStructures=true
; 中立建筑在占领它的所属方败北后回归中立所属
TeamRetaliate=true
; 重启 RA2 废掉的团队复仇，当小队成员被打时整个小队集体反击
DropPodTrailer=SMOKEY2
; 为 DropPod 启用 RA2 版通用尾烟
TypeSelectUseDeploy=false
; 禁用原版 DeploysInto 和 UndeploysInto 的自动分组，全面使用新增的 GroupAs 取代之
TogglePowerAllowed=true
; 开启切换电源，快捷键要去键位设置里调，本项目附赠自选组件中设为 O 键
TogglePowerDelay=45
; 切换电源的延迟
CloakHeight=120
; 该高度以下的单位才可以被 [BuildingType] -> CloakGenerator=yes 的建筑赋予隐形，原版为 0 以至于 Locomotor=Hover 的运输车和遥控坦克等无法被隐形
StealthSpeakDelay=1
; 探测到隐形单位时播报警告语音的间隔，单位：分钟
SubterraneanSpeakDelay=.3
; 探测到潜地单位时播报警告语音的间隔，单位：分钟
BountyEnablers=
; 拥有哪些建筑后开启赏金逻辑，默认 none 不开启，留空代表始终开启
EngineerCaptureLevel=.33
; 多工程师 - 建筑血量低于这里指定的比例才能占领，此前每次进入造成杀伤
EngineerDamage=.33
; 多工程师 - 造成杀伤时每次损伤建筑这么多比例的血量
EngineerAlwaysCaptureTech=true
; 多工程师 - 是否总是直接占领地图上的科技建筑而不使用上面的逻辑

; Phobos
FixTransparencyBlitters=false
; 更精确且性能更高的 RLE SHP 绘制算法，但多处反馈该逻辑导致原版动画颜色出现问题
BuildingProductionQueue=true
; 让建筑像其他类型单位一样可以使用建造队列，不习惯就关掉
BuildingTypeSelectable=true
; 允许建筑像 RA2 中那样选中后 T 选，YR 这按住 T 点下去才能 T 选的手感实在不太好
SortCameoByName=true
; 在默认图标排序规则的 UIName 对应 CSF 文本比较前插入对 Name= 的比较以避免在不同语言下图标乱序
UnitPowerDrain=true
; 允许非建筑类单位使用 Power= 设定发电量或电力消耗量，如果硬件性能不够好导致卡顿的话自己关掉
ArtImageSwap=true
; 允许非建筑类科技类型同样可以在 artmd.ini 中使用 Image= 调取其他美术资源文件作为图像，原版未生效且与此冲突的内容已被专门处理，若有遗漏项可以去 https://gitee.com/PB_LAB/yrstandard-ini/issues/new 反馈
RecountBurst=true
; 如果停火时 Burst 还没射完，是否无目标一段时间后将可用 Burst 余量填满而不是只保留射了一半没射完的量
BerzerkTargeting=team
; 让狂暴单位只能对己方和友方（对造成混乱一方来说的敌方）开火
AISuperWeaponDelay=0
; 让 AI 只要超武能发射就立即使用而忽略 106-112 帧的随机延迟，如果硬件性能不够好导致卡顿的话自己关掉
ChronoSparkleDisplayDelay=6
; 超时空冻结动画创建间隔
ChronoSparkleBuildingDisplayPositions=building,occupants
; 超时空冻结动画在建筑的哪个位置创建，原版为在所有驻军的枪口闪烁坐标处，现改为建筑自身中心和当前开火的驻军枪口闪烁坐标处，若要还原原有行为则改为 occupantslots
Storage.TiberiumIndex=-1
; 都有哪些类型的矿石可以存储在使用了 Ares 储矿功能的建筑中，默认 -1 即所有类型
AllowDeployControlledMCV=true
; 允许部署被心灵控制的 MCV，心灵控制链接会自动转移，不会像 YR1.000 那样直接刷漆
AnimCraterDestroyTiberium=false
; 禁止 Crater=yes 的动画摧毁矿石，可以通过 [Animation] -> Crater.DestroyTiberium 语句在动画上自定义
InfantryAutoDeploy=true
; 允许使用美国大兵式部署的步兵像 RA2 中那样在与敌人交战时会自动部署以使用火力更强的副武器
TypeSelectUseIFVMode=true
; 同一 IFV 单位的同武器模式个体间才能类选，避免类选时带着维修车一起冲锋。这通过使单位 WeaponGroupAsN 设定的二级组别默认为武器模式值来实现，若禁用则相当于 WeaponGroupAsN 全部默认为 0 即没有二级组别差分，你可以在单位上自行进行更细致的定义
HarvesterScanAfterUnload=true
; 令矿车在倒矿时执行一次矿区扫描而不是前往回来倒矿前记录的坐标，这可以避免矿车总是在远方流浪而忽略更近的矿区
NoTurret.TrackTarget=true
; 允许无炮塔单位在武器冷却期间就更新方向而不是等到能开火了才转身
MindControl.ThreatDelay=15
; 被心控的单位在 15 帧内不会受到来自友方单位的攻击以允许友军单位可以优先解决心控来源
ProneSpeed.Crawls=0.8
; 步兵匍匐时的移动速度倍率，原版为 0.67 倍
ProneSpeed.NoCrawls=1.5
; 步兵站立时的移动速度倍率，保留原版值
DamagedSpeed=0.8
; Locomotor=Drive/Ship 的单位在残血时的速度倍率，原版为 0.67 倍
JumpjetClimbPredictHeight=true
; Locomotor=Jumpjet 的单位将会提前 5 个单元格开始抬升而非仅在悬崖和建筑马上贴脸了才抬升高度
JumpjetClimbWithoutCutOut=true
; Locomotor=Jumpjet 的单位在已经抵近悬崖或建筑时将不会停止水平方向上的移动，而是在抬升高度的同时继续前行
SubterraneanHeight=-256
; Locomotor=Tunnel 的单位的地下水平移动高度，可在单位上微观定义，必须低于 -50 以避免异常行为
SubterraneanSpeed=19
; Locomotor=Tunnel 的单位的地下水平移动速度，可在单位上微观定义
NoQueueUpToEnter=true
; 载员逻辑 - 快速上车／进楼
NoQueueUpToUnload=true
; 载员逻辑 - 快速下车／弃楼
AIChronoSphereSW=ChronoSphereSpecial
; 56 超时空传送至建筑、57 超时空传送至目标 和 10104 超时空传送至敌方基地在传送原点使用的超武
; AIChronoWarpSW=ChronoWarpSpecial - 不定义以允许自动跟随上一条所用超武的 [SuperWeaponType] -> SW.PostDependent= 设定项
; 56 超时空传送至建筑、57 超时空传送至目标 和 10104 超时空传送至敌方基地在传送目标点使用的超武
AIFireSale=true
; AI 发现天要亡我时是否会卖家
AIFireSaleDelay=2700
; AI 要卖家的话会等待多少帧，原版为 0 直接拔线，这里改为中速下 3 分钟来确保冲锋在快速游戏开启的情况下可以有效抵达对面家里
AIAllToHunt=true
; AI 发现天要亡我时是否会冲锋
GatherWhenMCVDeploy=true
; AI 在载具部署为 [BuildingType] -> ConstructionYard=true 的建筑时是否会大军回防集结
DistributeTargetingFrame=true
; 分散索敌的初始间隔以避免所有单位集中在同一帧执行索敌造成卡顿
DistributeTargetingFrame.AIOnly=false
; 分散索敌是否仅作用于 AI 的单位，与此禁用，毕竟人类玩家也可以是防守图攻方拥有大量单位
AmphibiousEnter=true
; 载员逻辑 - 两栖单位可以在水上进入运输工具
AmphibiousUnload=true
; 载员逻辑 - 两栖单位可以在水上离开运输工具
AttackMove.Aggressive=false
; 移动中攻击时自动攻击敌方无武装建筑（侵略模式），如果想要保留无武装建筑就不要开
AttackMove.UpdateTarget=true
; 移动中自动切换威胁值较高的目标
AttackMove.StopWhenTargetAcquired=true
; 移动中攻击时若发现敌人则停止移动，可避免冲太快白送
AttackMove.IgnoreWeaponCheck=true
; 移动中攻击时是否禁用武器检查，可避免混选到无武装单位时被其阻止下达移动攻击指令
ExtendedAircraftMissions=true
; 开启扩展的战机任务
ExtendedAircraftMissions.UnlandDamage=0
; 当上条开启时无机场战机每 4 帧受到多少点杀伤，默认 -1 立即摧毁，但这会导致一些任务中从场外飞入的机场战机在执行完任务前就祭天，所以改为 0 禁用
GainSelfHealAllowMultiplayPassive=false
; 禁止中立治安通过科技医院和科技商店回血
GainSelfHealFromPlayerControl=true
; 允许所有 PlayerControl=true 的所属方通过科技医院和科技商店回血
GainSelfHealFromAllies=true
; 允许盟友间共享科技医院和科技商店回血

[ZEP]
AttackMove.PursuitTarget=true
; 即便开启 AttackMove.StopWhenTargetAcquired 也继续追击已锁定的单个目标

[IQ]
TogglePower=1
; 为 AI 开启自动切换电源

[CrateRules]
CrateOnlyOnLand=false
; 箱子是否仅在陆地上创建
UnitCrateVehicleCap=-1
; 单位箱子在拥有多少个载具后转为金钱箱子，当前改为一直开出载具而始终不转变，若要还原原版行为则改为 50
FreeMCV=true
; 资金充足但无建筑且无 MCV 时箱子中是否必然为 MCV
FreeMCV.CreditsThreshold=1500
; 上条中资金充足的判定下限

[CombatDamage]
IronCurtain.KeptOnDeploy=true
; 允许铁幕在 (Un)deploysInto 后继承而不是丢失
ForceShield.KeptOnDeploy=true
; 允许力场护盾在 (Un)deploysInto 后继承而不是丢失
IronCurtain.EffectOnOrganics=invulnerable
; 允许铁幕对有生单位生效
ForceShield.EffectOnOrganics=ignore
; 允许力场护盾忽略有生单位而不是压毙之
ROF.RandomDelay=0,0
; 全局禁用 ROF 随机延迟
AllowWeaponSelectAgainstWalls=false
; 是否默认开启主武 [Warhead] -> Wall=false 则对墙时自动切副武的规则，若开启可以在单个单位上使用 NoSecondaryWeaponFallback=true 来禁用，PhobosBuild46 新增
IvanBombAttachToCenter=true
; 使伊文炸弹的图像和引爆坐标处于建筑占地中心而不是原点单元格
AdjacentWallDamage=0
; 每个 [OverlayType] -> Wall=true 的覆盖物被摧毁时对周围 4 格内的其他墙造成多少伤害，原版为 200，这就导致多段墙连在一起时比单格围墙更容易被破坏

[AudioVisual]
; Ares
DropPodPuff=RING1
; 空降仓撞击地面的动画。仅占位，有需要自行替换
AtmosphereEntry=RING
; 空降仓进入大气层的动画。仅占位，有需要自行替换
BountyDisplay=true
; 赏金逻辑获得资金的数字是否显示
OnFire=INVISO,INVISO,INVISO
; FIRE1,FIRE2,FIRE4
TreeFire=INVISO,INVISO
; FIRE1,FIRE2
LargeFire=INVISO
; FIRE2
SmallFire=INVISO
; FIRE3
; 有人觉得爆了以后留下火焰和原版不一样，所以禁了，仅确保 Sparky=yes 打红血建筑不炸，想开自己开吧

DiskLaserAnimEnabled=true
; [Weapon] -> DiskLaser=true 的武器能否创建弹头动画，为了与原版效果保持一致，[DiskWH] 中的 AnimList 语句已被注释
InfantryElectrocuted=ELECTRO
; [Warhead] -> InfDeath=5 的弹头击杀步兵的默认动画，原版用 [Animations] 注册表下第 2 个，不便管理

; Phobos
ROF.RandomDelay=0,0
; 原版武器 ROF 有一个 0-2 之间的随机延迟
PlacementPreview=true
; 建筑虚影 - 开启
PlacementPreview.Translucency=75
; 建筑虚影 - 虚影透明度
PlacementGrid.Translucency=75
; 建筑虚影 - 不开启时摆放单元格的透明度
PlacementGrid.TranslucencyWithPreview=75
; 建筑虚影 - 在开启时摆放单元格的透明度
AircraftLevelLightMultiplier=0.8
; 战机由单元格高度所获得的亮度倍率，原版为 1.0
JumpjetLevelLightMultiplier=0.6
; Locomotor=Jumpjet 的单位由单元格高度所获得的亮度倍率，原版为 0.0
IronCurtain.ExtraTintIntensity=0.5
; 单位被铁幕效果作用的额外染色强度
ForceShield.ExtraTintIntensity=0.3
; 单位被力场护盾作用的额外染色强度
AnimRemapDefaultColorScheme=LightGold
; 拥有 [Animation] -> AltPalette=true 的动画在映射所属色但实际无所属时默认使用的配色方案，原版使用 [Colors] 列表第 1 个，不便管理
TimerBlinkColorScheme=LightGrey
; 超级武器计时器充满时与所属色交替闪烁的配色方案，原版使用 [Colors] 列表第 3 个，不便管理
; ColorAddUse8BitRGB=true
; [ColorAdd] 改用 RGB888 格式，需要 Build44 以上版本的 Phobos，若附带 Kratos 则目前 v0.1.15 下无效
ToolTip.Background.Opacity=40
; 工具条背景的不透明度
ToolTip.Background.BlurSize=.80
; 工具条背景的模糊程度
AirShadowBaseScale=0.7
; ConsideredAircraft=true 单位的基础影子尺寸倍率，原版为 0.5
HeightShadowScaling=true
; 开启影子尺寸跟随高度改变
HeightShadowScaling.MinScale=0.1
; 在上条时的影子倍率最小值
DrawTurretShadow=true
; 开启载具炮塔影子
WarheadParticleAlphaImageIsLightFlash=true
; 将由弹头创建的粒子系统及粒子上的 AlphaImage 效果也计入闪光效果
LightFlashAlphaImageDetailLevel=1
; 设置这些 AlphaImage 光效仅在画质级别至少 1 时创建
CombatLightDetailLevel=1
; 设置战斗闪光效果仅在画质级别至少 1 时创建
Parasite.GrappleAnim=SQDG
; 海军有生寄生单位（乌贼）拖拽舰船时的默认动画，可在弹头上微观定义
RadialIndicatorVisibility=all
; 允许所有所属方可见建筑范围指示环而不再仅限友军
SelectionFlashDuration=15
; 选中单位时使其闪烁 15 帧，若有附加单位则默认情况下跟随主体闪烁
SuperWeaponSidebar.AllowByDefault=false
; 超武默认不进入侧边栏，侧边栏空位有限，为真加入更符合逻辑
ShowDesignatorRange=true
; 显示超武指示者范围
DisplayIncome=true
; 开启回收站等的资金显示
DisplayIncome.AllowAI=false
; 有人看见 AI 一车矿是自己的好几倍就应激了
MissingCameo=XXICON.SHP
; 缺省时备用的默认图标
CombatAlert=true
; 为当前屏幕外的己方单位受伤时添加警报，如果觉得吵就关掉
Promote.VeteranAnimation=Veteran
; 单位老兵时播放的动画
Promote.EliteAnimation=Veteran
; 单位精英时播放的动画
AirstrikeLineColor=255,25,25
; 空袭指引激光颜色
WarheadAnimZAdjust=0
; 禁用弹头动画 Z 深设置，使用动画类型自身通过[Animation] -> ZAdjust=设置的 Z 深，如果这对已有动画的图层影响很大而又不想逐个动画更改那么将此值设为-15

[ColorAdd]:[ColorAdd565]
; 若开启 ColorAddUse8BitRGB=true 则将上一行的 565 改为 888 即可，此处使用 INI 继承功能进行关联调用

; Ares 自定义光标，下面是原版已有的各固定光标的参数，若无需修改原有光标可忽略
[MouseCursors]
Default=0,1,0,1,1,Left,Top
MoveN=2,1,0,-1,-1,Center,Top
MoveNE=3,1,0,-1,-1,Right,Top
MoveE=4,1,0,-1,-1,Right,Middle
MoveSE=5,1,0,-1,-1,Right,Bottom
MoveS=6,1,0,-1,-1,Center,Bottom
MoveSW=7,1,0,-1,-1,Left,Bottom
MoveW=8,1,0,-1,-1,Left,Middle
MoveNW=9,1,0,-1,-1,Left,Top
NoMoveN=10,1,0,-1,-1,Center,Top
NoMoveNE=11,1,0,-1,-1,Right,Top
NoMoveE=12,1,0,-1,-1,Right,Middle
NoMoveSE=13,1,0,-1,-1,Right,Bottom
NoMoveS=14,1,0,-1,-1,Center,Bottom
NoMoveSW=15,1,0,-1,-1,Left,Bottom
NoMoveW=16,1,0,-1,-1,Left,Middle
NoMoveNW=17,1,0,-1,-1,Left,Top
Select=18,13,4,-1,-1,Center,Middle
Move=31,10,4,42,10,Center,Middle
NoMove=41,1,0,52,1,Center,Middle
Attack=53,5,4,63,5,Center,Middle
AttackOutOfRange=58,5,4,63,5,Center,Middle
DesolatorDeploy=78,10,4,-1,10,Center,Middle
Enter=89,10,4,100,10,Center,Middle
NoEnter=99,1,0,63,1,Center,Middle
Deploy=110,9,4,-1,-1,Center,Middle
NoDeploy=119,1,0,-1,-1,Center,Middle
Sell=129,10,4,-1,-1,Center,Middle
SellUnit=139,10,4,-1,-1,Center,Middle
NoSell=149,1,0,-1,-1,Center,Middle
Repair=150,20,4,-1,-1,Center,Middle
EngineerRepair=170,20,4,-1,-1,Center,Middle
NoRepair=190,1,0,-1,-1,Center,Middle
Disguise=199,5,0,-1,-1,Center,Middle
IvanBomb=204,5,4,-1,-1,Center,Middle
MindControl=209,5,0,-1,-1,Center,Middle
RemoveSquid=214,5,0,-1,-1,Center,Middle
Crush=219,5,0,-1,-1,Center,Middle
SpyTech=224,5,0,-1,-1,Center,Middle
SpyPower=229,5,0,-1,-1,Center,Middle
GIDeploy=239,10,0,-1,-1,Center,Middle
Paradrop=259,10,4,516,-1,Center,Middle
LightningStorm=279,20,4,514,1,Center,Middle
Detonate=299,10,4,-1,-1,Center,Middle
Demolish=309,10,4,-1,-1,Center,Middle
Nuke=319,10,4,513,1,Center,Middle
IronCurtain=346,5,4,-1,-1,Center,Middle
Chronosphere=357,12,4,-1,-1,Center,Middle
Disarm=369,15,0,-1,-1,Center,Middle
Scroll=385,1,0,-1,-1,Center,Middle
ScrollESW=386,1,0,-1,-1,Center,Middle
ScrollSW=387,1,0,-1,-1,Center,Middle
ScrollNSW=388,1,0,-1,-1,Center,Middle
ScrollNW=389,1,0,-1,-1,Center,Middle
ScrollNEW=390,1,0,-1,-1,Center,Middle
ScrollNE=391,1,0,-1,-1,Center,Middle
ScrollNES=392,1,0,-1,-1,Center,Middle
ScrollES=393,1,0,-1,-1,Center,Middle
AttackMove=404,9,4,63,5,Center,Middle
InfantryAbsorb=422,9,4,-1,-1,Center,Middle
NoMindControl=431,1,0,-1,-1,Center,Middle
Beacon=435,15,4,-1,-1,Center,Middle
ForceShield=450,10,4,-1,1,Center,Middle
NoForceShield=460,10,4,-1,-1,Center,Middle
GeneticMutator=470,10,4,-1,-1,Center,Middle
AirStrike=480,8,4,-1,-1,Center,Middle
PsychicDominator=488,8,4,516,-1,Center,Middle
PsychicReveal=496,8,4,515,1,Center,Middle
SpyPlane=504,8,4,512,1,Center,Middle
Tote=329,10,4,-1,-1,Center,Middle
EngineerDamage=299,10,4,-1,-1,Center,Middle
TogglePower=339,6,0,-1,-1,Center,Middle
NoTogglePower=384,1,0,-1,-1,Center,Middle
InfantryHeal=355,1,0,-1,-1,Center,Middle
UnitRepair=150,20,4,-1,-1,Center,Middle
TakeVehicle=89,10,4,100,10,Center,Middle
Sabotage=89,10,4,100,10,Center,Middle
RepairTrench=150,20,4,-1,-1,Center,Middle

; 低优先级框选
[HORNET]
LowSelectionPriority=true
[ASW]
LowSelectionPriority=true
[SLAV]
LowSelectionPriority=true
[HARV]
LowSelectionPriority=true
[HORV]
LowSelectionPriority=true
[CMIN]
LowSelectionPriority=true
[CMON]
LowSelectionPriority=true
[SMIN]
LowSelectionPriority=true
[SMON]
LowSelectionPriority=true

[HARV]
Harvester.CanGuardArea=true
; 允许矿车按 G 执行区域警戒时不会直接转为采矿任务
Harvester.CanGuardArea.RequireTarget=true
; 如果警戒范围内没有可用目标则仍会转为采矿任务

; Phobos 超武侧边栏相关文件指定及预添加三阵营大小超武

[ForceShieldSpecial]
SuperWeaponSidebar.Allow=true
; 还有此功能最最最好用的力场护盾 (;-_-)
SuperWeaponSidebar.Significance=3

[ParaDropSpecial]
SuperWeaponSidebar.Allow=true
; 原版科技机场伞兵
SuperWeaponSidebar.Significance=2

[GDI]
SuperWeaponSidebar.OnPCX=swside01on.pcx
SuperWeaponSidebar.OffPCX=swside01off.pcx
SuperWeaponSidebar.TopPCX=swside01top.pcx
SuperWeaponSidebar.CenterPCX=swside01center.pcx
SuperWeaponSidebar.BottomPCX=swside01bottom.pcx

[LightningStormSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=3
SuperWeaponSidebar.PriorityHouses=British,French,Germans,Americans,Alliance
SuperWeaponSidebar.RequiredHouses=British,French,Germans,Americans,Alliance
[ChronoSphereSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=2
SuperWeaponSidebar.PriorityHouses=British,French,Germans,Americans,Alliance
SuperWeaponSidebar.RequiredHouses=British,French,Germans,Americans,Alliance
[AmericanParaDropSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=1
SuperWeaponSidebar.PriorityHouses=British,French,Germans,Americans,Alliance
SuperWeaponSidebar.RequiredHouses=British,French,Germans,Americans,Alliance

[Nod]
SuperWeaponSidebar.OnPCX=swside02on.pcx
SuperWeaponSidebar.OffPCX=swside02off.pcx
SuperWeaponSidebar.TopPCX=swside02top.pcx
SuperWeaponSidebar.CenterPCX=swside02center.pcx
SuperWeaponSidebar.BottomPCX=swside02bottom.pcx

[NukeSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=3
SuperWeaponSidebar.PriorityHouses=Russians,Confederation,Africans,Arabs
SuperWeaponSidebar.RequiredHouses=Russians,Confederation,Africans,Arabs
[IronCurtainSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=2
SuperWeaponSidebar.PriorityHouses=Russians,Confederation,Africans,Arabs
SuperWeaponSidebar.RequiredHouses=Russians,Confederation,Africans,Arabs
[SpyPlaneSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=1
SuperWeaponSidebar.PriorityHouses=Russians,Confederation,Africans,Arabs
SuperWeaponSidebar.RequiredHouses=Russians,Confederation,Africans,Arabs

[ThirdSide]
SuperWeaponSidebar.OnPCX=swside02on.pcx
SuperWeaponSidebar.OffPCX=swside02off.pcx
SuperWeaponSidebar.TopPCX=swside02top.pcx
SuperWeaponSidebar.CenterPCX=swside02center.pcx
SuperWeaponSidebar.BottomPCX=swside02bottom.pcx

[PsychicDominatorSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=3
SuperWeaponSidebar.PriorityHouses=YuriCountry
SuperWeaponSidebar.RequiredHouses=YuriCountry
[GeneticConverterSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=2
SuperWeaponSidebar.PriorityHouses=YuriCountry
SuperWeaponSidebar.RequiredHouses=YuriCountry
[PsychicRevealSpecial]
SuperWeaponSidebar.Allow=true
SuperWeaponSidebar.Significance=1
SuperWeaponSidebar.PriorityHouses=YuriCountry
SuperWeaponSidebar.RequiredHouses=YuriCountry

; 按当前设计，用户所需等级对应关系如下：
3 - 大超武与力场护盾
2 - 小超武与科技机场伞兵
1 - 美国伞兵、侦察机、心灵探测
仅当一个超武的 Significance= 值不低于用户在 ra2md.ini 中设定的 [Phobos] -> SuperWeaponSidebar.RequiredSignificance= 时才会显示在侧边栏中

; End

; 通过 Ares 新增阵营默认值设置为原版三阵营分离设置残兵工程师
[GDI]
Engineer=ENGINEER

[NOD]
Engineer=SENGINEER

[ThirdSide]
Engineer=YENGINEER

; 这部分是用于处理 XNA CNCNet Client 启动游戏后按 Tab 键闪退问题的
[Africans]
File.Flag=cflag_africans.pcx

[Alliance]
File.Flag=cflag_alliance.pcx

[Americans]
File.Flag=cflag_americans.pcx

[Arabs]
File.Flag=cflag_arabs.pcx

[British]
File.Flag=cflag_british.pcx

[Confederation]
File.Flag=cflag_confederation.pcx

[French]
File.Flag=cflag_french.pcx

[Germans]
File.Flag=cflag_germans.pcx

[Russians]
File.Flag=cflag_russians.pcx

[YuriCountry]
File.Flag=cflag_yuricountry.pcx

; End

[WeaponTypes]
; Ares 有效，直接使用这个注册表来注册子武器而无需用一个 XCOMET 和 WEEDGUY 那样的虚拟单位挂载
+=CometFragment
+=TeslaFragment
+=SuperCometFragment
; Ares有效，使用 += 而不必须不重复序号来注册

[Animations]
+=SMOKEY
+=FLHAEANIM
+=Counter_0
+=Counter_1

[ArmorTypes]
hutarmor=0%

[CABHUT]
Armor=hutarmor

[CAOILD]
ProduceCashDisplay=true

[AudioVisual]
DigSound=dummy
; 屏蔽全局 DigSound，使用 Ares 标签重新【在超武上】指定，否则钻地车钻地会发出核弹发射警报全图音效
[NukeSpecial]
SW.ActivationSound=NukeSiren

; Ares 为了复原 RA1 逻辑允许了战机驾驶员逃生，但很多人不太习惯并且受困于其对防空火力分配的影响
[ORCA]
Crewed=no
[BEAG]
Crewed=no
[PDPLANE]
Crewed=no
[BPLN]
Crewed=no
[SPYP]
Crewed=no
; 复原被 Ares 更改的 YR 行为

[NALASR]
Powered=false
; 从 TS 遗留下来的设置，在 Ares 下这会导致哨戒炮默认可被 EMP 瘫痪

[SCHP]
DeathWeapon=BlimpBombEffect
DeathWeaponDamageModifier=.1
; 给 SCHP 开了 BalloonHover，用这个避免坠毁时调用主武留下一堆子弹动画

; 用 GroupAs 重建原版 DeploysInto 的类选分组

[AMCV]
GroupAs=AlliedBase

[GACNST]
GroupAs=AlliedBase

[SMCV]
GroupAs=SovietBase

[NACNST]
GroupAs=SovietBase

[PCV]
GroupAs=YuriBase

[YACNST]
GroupAs=YuriBase

[SMIN]
GroupAs=SlaveMiner

[YAREFN]
GroupAs=SlaveMiner

; 将原版全局伞兵（仅可使用步兵）使用 Ares 自定义伞兵超武重写，以便添加载具类载员等其他设定

[AmericanParaDropSpecial]
ParaDrop.Aircraft=PDPLANE
ParaDrop.Types=E1
ParaDrop.Num=8

[ParaDropSpecial]
ParaDrop.GDI.Aircraft=PDPLANE
ParaDrop.GDI.Types=E1
ParaDrop.GDI.Num=6

ParaDrop.Nod.Aircraft=PDPLANE
ParaDrop.Nod.Types=E2
ParaDrop.Nod.Num=9

ParaDrop.ThirdSide.Aircraft=PDPLANE
ParaDrop.ThirdSide.Types=INIT
ParaDrop.ThirdSide.Num=6

; 写法：
; ParaDrop(.<阵营/国家>).Aircraft=作为运输机的单个飞机
; ParaDrop(.<阵营/国家>).Types=单位1,单位2,...
; ParaDrop(.<阵营/国家>).Num=单位1数量,单位2数量,...
; 示例：
; ParaDrop.Nod.Aircraft=BPLN
; ParaDrop.Nod.Types=BORIS,APOC
; ParaDrop.Nod.Num=9,2
; 更详细的示例和解释见 Ares 说明书

; 启用原版未使用的 EVA 播报
[ParaDropSpecial]
EVA.Ready=EVA_ParatroopersReady
; 美国伞兵遵照原版硬编码和 Ares 默认值使用 EVA_ReinforcementsReady 作为 Ready 的 EVA 播报音频故不进行人为定义

[ForceShieldSpecial]
EVA.Activated=EVA_ForceShieldActivated

[SpyPlaneSpecial]
EVA.Activated=EVA_SpyPlaneEnRoute

; 数字化显示，自定义见 Phobos 官方文档https://phobos.readthedocs.io/zh-cn/latest/User-Interface.html#digital-display
[DigitalDisplayTypes]
+=DefaultDigitalType

[AudioVisual]
Buildings.DefaultDigitalDisplayTypes=DefaultDigitalType
Infantry.DefaultDigitalDisplayTypes=DefaultDigitalType
Vehicles.DefaultDigitalDisplayTypes=DefaultDigitalType
Aircraft.DefaultDigitalDisplayTypes=DefaultDigitalType

[DefaultDigitalType]
Shape=digits.shp

; 通过 Ares 语句重定义原版导弹子机参数
[V3ROCKET]
Missile.Custom=true
Missile.PauseFrames=0
Missile.TiltFrames=60
Missile.PitchInitial=0.21
Missile.PitchFinal=0.5
Missile.TurnRate=0.05
Missile.RaiseRate=1
Missile.Acceleration=0.4
Missile.Altitude=768
Missile.Damage=200
Missile.EliteDamage=400
Missile.BodyLength=256
Missile.LazyCurve=yes
Missile.Warhead=V3WH
Missile.EliteWarhead=V3EWH
Missile.TakeOffAnim=V3TAKOFF
Missile.TrailerAnim=V3TRAIL
Missile.TrailerSeparation=3

[DMISL]
Missile.Custom=true
Missile.PauseFrames=20
Missile.TiltFrames=60
Missile.PitchInitial=0
Missile.PitchFinal=0.5
Missile.TurnRate=0.08
Missile.RaiseRate=1
Missile.Acceleration=0.8
Missile.Altitude=768
Missile.Damage=300
Missile.EliteDamage=600
Missile.BodyLength=128
Missile.LazyCurve=no
Missile.Warhead=DMISLWH
Missile.EliteWarhead=DMISLEWH
Missile.TakeOffAnim=V3TAKOFF
Missile.TrailerAnim=V3TRAIL
Missile.TrailerSeparation=3

[CMISL]
Missile.Custom=false
; 不能使用自定义导弹，因为现代公版引擎仍未解决副作用
Missile.TakeOffAnim=V3TAKOFF
Missile.TrailerAnim=V3TRAIL
Missile.TrailerSeparation=3

[BFRT]
OmniCrusher.Aggressive=no

; 看不懂的标签请自行查阅说明书和词典